# Use the C++ base image
FROM mcr.microsoft.com/devcontainers/cpp

# Install cmake 3.25
RUN curl -L "https://cmake.org/files/v3.27/cmake-3.27.7-linux-x86_64.tar.gz" | tar xz --strip-components=1 -C /usr/local/
